# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e0850eaaadd9d47036285dabf28c9471d130fa0a4d3779e07fefa8ceebbaae12cdc5f9dd0592d5d93f0d257bcc0a6783b9f8b7622494f421a72b31a3fe020434

test:
  secret_key_base: 25c722fa5dc5bf5e05c3f40da31c392d25f8d6b49233e8a18d57d307b924e92e9a00ff127a7a88d53bc05589bc2419b27e1279121c0b8644d8c1b1cdd3035c78

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
